[project]
authors = [
    { name = "Mohamed El Morabity", email = "melmorabity@fedoraproject.org" },
]
classifiers = [
    "Environment :: Console",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Security",
]
description = "A Trivy plugin that enhances vulnerability scan results with EPSS data"
keywords = ["epss", "plugin", "trivy", "trivy-scan"]
license = { text = "GPL-3.0-or-later" }
name = "trivy-plugin-epss"
readme = "README.md"
requires-python = ">=3.10"
version = "1.1.0"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project.optional-dependencies]
dev = [
    "pre-commit",
    "python-semantic-release",
    "ruff",
    "trivy-plugin-epss[test]",
    "ty",
    "typing_extensions",
]
test = ["pyfakefs", "pytest", "pytest-cov", "pytest-mock", "tox", "tox-uv"]

[tool.pytest.ini_options]
addopts = [
    "--cov-fail-under=100",
    "--cov-report=term-missing",
    "--cov-report=xml",
    "--cov=epss",
]

[tool.ruff]
line-length = 79
preview = true
target-version = "py310"

[tool.ruff.format]
skip-magic-trailing-comma = true

[tool.ruff.lint]
ignore = ["COM812", "CPY001", "EM", "FBT", "LOG015", "TRY003", "TRY400"]
select = ["ALL"]

[tool.ruff.lint.flake8-type-checking]
strict = true

[tool.ruff.lint.isort]
order-by-type = false
split-on-trailing-comma = false

[tool.ruff.lint.per-file-ignores]
"tests.py" = ["D", "PLR0913", "PLR0917", "S101"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.tox]
legacy_tox_ini = """
[tox]
min_version = 4.0
requires =
    tox-uv
envlist = py310,py311,py312,py313,py314
skip_missing_interpreters = False

[testenv]
runner = uv-venv-runner
uv_python_preference = only-managed
set_env =
    UV_PYTHON_DOWNLOADS = automatic
deps = -e .[test]
commands = pytest tests.py

[testenv:lint]
deps = -e .[dev]
commands =
  pre-commit run -a
"""

[tool.semantic_release]
commit_message = "chore(release): {version}\n\nAutomatically generated by python-semantic-release"
version_toml = ["pyproject.toml:project.version"]
version_variables = ["README.md:trivy-plugin-epss:tf", "plugin.yaml:version:nf"]

[tool.ty.environment]
python-version = "3.10"
